[package]
name = "day1"
version = "0.1.0"
authors = ["Ben Maguire <benjamin.maguire@govteams.gov.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common  = { path = "../common" }
itertools = "0.10.*"